"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 500

[character]
error_symbol = "[â¯](bold red)"
format = "$symbol "
success_symbol = "[â¯](bold green)"

[git_branch]
symbol = "ğŸŒ± "

[time]
disabled = false
format = '\[ $time \]]($style) '
